<?php
session_start();

if($_SESSION["unamef"]==true)
{

}
else
{
header('location:stu.php');
}
?>

<html>
<head>

<title>ON PROCESS</title>
    <link rel="stylesheet" type="text/css" href="style.css" media="all" />
    <link rel="stylesheet" type="text/css" href="demo.css" media="all" />
</head>
<body>
<div class="container">
			
            <div class="freshdesignweb-top">
                <a href="faculty.php">Home</a>
                <span class="right">
                    <a href="logout.php">
                        <strong>logout</strong>
                    </a>
                </span>
                
            </div>
			<header>
			<br><br><br><br><br><br><br>
				<h1><h1><h1><h1>WORK ON PROCESS </h1></h1></h1></h1>
            </header>        
           
</div>


<body>
</body>
</html>
